# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FileTextIO": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://arunabha.github.io/modules_practice/"

git_url = "https://github.com/arunabha/modules_practice/tree/master/"

def custom_doc_links(name): return None
