# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['FileTextIO']

# Cell
import os

class FileTextIO:
    """Represents a standard text file read and write

    Attributes:
        file_name: str
    """
    file_name = "default.txt"

    def __init__(self, file_name = ""):
        if file_name:
            self.file_name = file_name

    def __str__(self):
        return '%s is ready for read and write' % (self.file_name)

    def read(self):
        """
        read the written file
        """
        if os.path.exists(self.file_name):
            with open(self.file_name, "r") as handle:
                return handle.readlines()
        else:
            print("File does not exists!")

    def write(self, content = ""):
        if content:
            with open(self.file_name, "w+") as handle:
                handle.writelines(content)
        else:
            print("Please provide content!")